### ISSUE TITLE
Move logic from citestwheel script into the test workflow

### ISSUE THREAD

**Issue by vyasr** [rapidsai/shared-action-workflows#81]
Currently wheel testing logic is contained in [a script embedded directly into the citestwheel image](https://github.com/rapidsai/cibuildwheel-imgs/blob/main/ciwheel/citestwheel.sh). The work here should proceed in two steps:
1. Move this logic from the image into the test workflows. 
2. Move the logic into scripts contained in each repo using the workflow. This step is only useful when we reach the stage of migrating the majority of workflow logic into scripts that can be handled by each repo using the workflow.

Would recommend tackling this after #79 since any attempt before then will duplicate code.

**Comment by wence-** [comment]
1. is relatively straightforward, 2. runs into the potential trouble that now we're back to replicating boilerplate in all the repositories individually.

Possible proposal is that the `wheels-test` workflow sets up the environment and then the repo caller does something like:
```yaml
uses: wheels-test.yml
with:
   ....
run: |
    # set project-specific commands
    # call new gha-tools command that does equivalent of the old citestwheel script
```
